[package]
name = "converter3dlc"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
eframe = "0.25.0"
egui_extras = "0.25.0"
egui = "0.25.0"
palette = "0.7.3"
image = "0.24.8"
imageproc = "0.23.0"
